# Generated by Django 4.2 on 2023-12-09 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sehir', models.CharField(max_length=50)),
                ('mahalle', models.CharField(max_length=100)),
                ('sokak', models.CharField(max_length=100)),
                ('bina', models.CharField(max_length=100)),
                ('daire', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'adresler',
            },
        ),
    ]
